POST http://localhost:8080/api/plan HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzUzMjMyNDA5LCJleHAiOjE3NTMzMTg4MDl9._1jHr5r6Cg-qSbtfoKbAaif6Z_z0OB8lJTxDxsbvxMY

{
    "departure": "의정부시",
    "travelId": 33,
    "dates": ["2025-08-22", "2025-08-23", "2025-08-24"],
    "adultCount": 2,
    "childCount": 2,
    "transportation": 1
}

###


PATCH  http://localhost:8080/api/plan/4/name
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzUzMjMyNDA5LCJleHAiOjE3NTMzMTg4MDl9._1jHr5r6Cg-qSbtfoKbAaif6Z_z0OB8lJTxDxsbvxMY

{"planName": "똥!ㅋㅋ"}