POST http://localhost:8080/api/plan HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNzUzMTkzNjc3LCJleHAiOjE3NTMyODAwNzd9.LtWB05zsBHGg-FwaGOnbgSmfqqcoXc3MvP_SWyfF51Q

{
    "departure": "의정부시",
    "travelId": 33,
    "dates": ["2025-08-22", "2025-08-23"],
    "adultCount": 2,
    "childCount": 2,
    "transportation": 1
}

###

PATCH http://localhost:8080/api/plan/1/title
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNzUzMTkzNjc3LCJleHAiOjE3NTMyODAwNzd9.LtWB05zsBHGg-FwaGOnbgSmfqqcoXc3MvP_SWyfF51Q

{"planName": "테스트"}