POST http://localhost:8080/api/plan HTTP/1.1
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzUzMjMyNDA5LCJleHAiOjE3NTMzMTg4MDl9._1jHr5r6Cg-qSbtfoKbAaif6Z_z0OB8lJTxDxsbvxMY

{
    "departure": "의정부시",
    "travelId": 33,
    "dates": ["2025-08-22", "2025-08-23", "2025-08-24"],
    "adultCount": 2,
    "childCount": 2,
    "transportation": 1
}

###


GET https://pmserver.salmakis.online/api/user/profile
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzU0MzMxMDcxLCJleHAiOjE3NTQ0MTc0NzF9.RjWjVPszBjM5enlVUUHtfoxBeEbSt2Uz7Sm2O5f6Ufc

//{"planName": "똥!ㅋㅋ"}

###

GET https://pmserver.salmakis.online/api/plan/79
Content-Type: application/json; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzU0ODAwMzIwLCJleHAiOjE3NTQ4ODY3MjB9.fh9ZoKS8d5c1rw-SnShneu-lX-iu18uZMAIqS-DDbcg

###

POST http://localhost:8080/api/plan/4/restaurant
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzUzMjMyNDA5LCJleHAiOjE3NTMzMTg4MDl9._1jHr5r6Cg-qSbtfoKbAaif6Z_z0OB8lJTxDxsbvxMY

### 

PATCH http://localhost:8080/api/plan/4/save
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNzUzMjMyNDA5LCJleHAiOjE3NTMzMTg4MDl9._1jHr5r6Cg-qSbtfoKbAaif6Z_z0OB8lJTxDxsbvxMY
Content-Type: application/json; charset=UTF-8

{
    "departure": "풍산역",
    "travel": "종로구",
    "adultCount": 2,
    "childCount": 1,
    "transportationCategoryId": 0,
    "timetables": [
    {
    "timetableId": 8,
    "date": "2025-08-22",
    "startTime": "09:00:00",
    "endTime": "20:00:00"
    },
    {
    "timetableId": 9,
    "date": "2025-08-23",
    "startTime": "09:00:00",
    "endTime": "20:00:00"
    },
    {
    "timetableId": 10,
    "date": "2025-08-24",
    "startTime": "09:00:00",
    "endTime": "20:00:00"
    }
    ],
   "timetablePlaceBlocks": [
    [
      {
        "timetablePlaceBlockId": 1,
        "placeCategory": 1,
        "placeName": "경복궁",
        "placeTheme": "역사",
        "placeRating": 4.7,
        "placeAddress": "서울 종로구 사직로 161",
        "placeLink": "https://map.example.com/place1",
        "date": "2025-07-22",
        "startTime": "09:00",
        "endTime": "10:30",
        "xLocation": 126.9769,
        "yLocation": 37.5796
      },
      {
        "timetablePlaceBlockId": 2,
        "placeCategory": 1,
        "placeName": "광화문광장",
        "placeTheme": "시민",
        "placeRating": 4.2,
        "placeAddress": "서울 종로구 세종대로",
        "placeLink": "https://map.example.com/place2",
        "date": "2025-07-22",
        "startTime": "10:45",
        "endTime": "11:30",
        "xLocation": 126.977,
        "yLocation": 37.5714
      }
    ],
    [
      {
        "timetablePlaceBlockId": 3,
        "placeCategory": 1,
        "placeName": "인사동 거리",
        "placeTheme": "쇼핑",
        "placeRating": 4.3,
        "placeAddress": "서울 종로구 인사동",
        "placeLink": "https://map.example.com/place3",
        "date": "2025-07-23",
        "startTime": "13:00",
        "endTime": "14:30",
        "xLocation": 126.9863,
        "yLocation": 37.574
      }
    ]
  ]
}
